services:
  frontend-cadastroclientesddc:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "3000:3000"
    networks:
      - pi_default
networks:
  pi_default:
    external: true